name: CI/CD Pipeline

on:
  push:
    branches: [production]
  pull_request:
    branches: [production]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      run: git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} .

    - name: Python 3.12 installieren
      run: |
        sudo apt update
        sudo apt install python3.12 python3.12-venv python3.12-dev -y

    - name: venv und requirements installieren
      run: |
        python3.12 -m venv .venv
        .venv/bin/pip install -r requirements.txt

    - name: Tests laufen lassen
      run: |
        .venv/bin/pip install pytest httpx
        .venv/bin/pytest tests/

    - name: Harbor einloggen
          if: github.ref == 'refs/heads/production'
          env:
            HARBOR_USER: ${{ secrets.HARBOR_USERNAME }}
            HARBOR_PASS: ${{ secrets.HARBOR_PASSWORD }}
          run: echo "$HARBOR_PASS" | docker login harbor.j-becker.org -u "$HARBOR_USER" --password-stdin

    - name: Docker Image bauen
      if: github.ref == 'refs/heads/production'
      run: |
        docker build -t harbor.j-becker.org/cicd-playground-k8s/${{ github.event.repository.name }}:latest \
                     -t harbor.j-becker.org/cicd-playground-k8s/${{ github.event.repository.name }}:${{ github.sha }} .

    - name: Image pushen
      if: github.ref == 'refs/heads/production'
      run: |
        docker push harbor.j-becker.org/cicd-playground-k8s/${{ github.event.repository.name }}:latest
        docker push harbor.j-becker.org/cicd-playground-k8s/${{ github.event.repository.name }}:${{ github.sha }}